
page = css('.page')
  .position('absolute')
  .top(0)
  .bottom(0)
  .left(0)
  .right(0)

nav = page.child('.nav')
  .position('absolute')
  .top(0).left(0).right(0)
  .textOverflow('ellipsis')
  .height(style.navHeight)
  .lineHeight(style.navHeight-style.statusBarHeight)
  .pt(style.statusBarHeight)
  .fontSize(style.navFontSize)
  .textAlign('center')
  .color(colors.primaryText)
  .bg(colors.primary)

left = nav.child('.left')
  .position('absolute')
  .top(style.statusBarHeight)
  .left(0)
  .height(style.navHeight-style.statusBarHeight)
  .pl(style.contentPadding)

right = nav.child('.right')
  .position('absolute')
  .top(style.statusBarHeight)
  .right(0)
  .height(style.navHeight-style.statusBarHeight)
  .pr(style.contentPadding)

statusBar = nav.child('.statusbar')
  .position('absolute')
  .top(0)
  .right(0)
  .left(0)
  .height(style.statusBarHeight)
  .bg('black')

content = page.child('.content')
  .position('absolute')
  .top(style.navHeight)
  .bottom(0)
  .left(0)
  .right(0)
  .color(colors.backgroundText)
  .bg(colors.background)
  .padding(style.contentPadding)