button = css('button')
  .margin(0)
  .pl(12).pr(12)
  .minWidth(52)
  .minHeight(47)
  .borderWidth(1)
  .borderStyle('solid')
  .borderColor('#555555')
  .borderRadius(2)
  .textAlign('center')
  .textOverflow('ellipsis')
  .fontSize(16)
  .lineHeight(42)
  .cursor('pointer')


button.also(':hover').textDecoration('none')
button.also('.block').w(100, 'pc')

button.also('.bar')
  .w("calc(100% + #{style.contentPadding*2}px)")
  .margin("10px -#{style.contentPadding}px")
  .borderRadius(0)
  .borderLeft('none')
  .borderRight('none')